In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,2,5]])
arr

array([[1, 2, 3],
       [4, 2, 5]])

In [3]:
print(arr)

[[1 2 3]
 [4 2 5]]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
x = [1,2,3]
print(type(x))

<class 'list'>


In [8]:
print(arr.ndim)

2


In [10]:
arr1 = np.array([[[1,2,3],
               [4,2,5]]])
print(arr1)

[[[1 2 3]
  [4 2 5]]]


In [11]:
print(arr1.ndim)

3


In [12]:
print(arr.shape)

(2, 3)


In [13]:
print(arr1.shape)

(1, 2, 3)


In [20]:
print(arr.size)

6


In [21]:
print(arr1.size)

6


In [22]:
print(arr.dtype)

int32


In [23]:
import numpy as np
l=[[1,2,3],[4,5,6],['a','b','c']]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.dtype)

[['1' '2' '3']
 ['4' '5' '6']
 ['a' 'b' 'c']]
<class 'numpy.ndarray'>
<U11


In [24]:
arr

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c']], dtype='<U11')

In [25]:
arr.ndim

2

In [26]:
arr.shape

(3, 3)

In [27]:
z = np.array([[[1,2],[3,4]],
             [[5,6],[7,8]]])
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
z.shape

(2, 2, 2)

In [30]:
arr2 = np.array([[1,2,3],
               [4,2,5]], dtype = "float")
arr2

array([[1., 2., 3.],
       [4., 2., 5.]])

In [32]:
arr = np.array([[1,2,3],
               [4,2,5]])
arr

array([[1, 2, 3],
       [4, 2, 5]])

In [33]:
b = np.array((1,3,2))
b

array([1, 3, 2])

In [34]:
b.ndim

1

In [35]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
f = np.full((3,3),6,dtype = 'float')
f

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [39]:
f = np.full((3,3),'a')
f

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [40]:
f.dtype

dtype('<U1')

In [41]:
f = np.full((3,3),'a',dtype = 'str')
f

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [43]:
x = np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
e = np.random.random((2,2))
e

array([[0.39930296, 0.45950703],
       [0.81599597, 0.93701518]])

In [70]:
f = "here is a string"
print(f[::2])

hr sasrn


In [73]:
g = np.arange(0,30,2)
g

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [74]:
h = np.linspace(0,5,10)
h

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [76]:
i = np.array([[1,2,3,4],
             [5,3,4,5],
             [1,2,1,3]])
i

array([[1, 2, 3, 4],
       [5, 3, 4, 5],
       [1, 2, 1, 3]])

In [77]:
i.shape

(3, 4)

In [78]:
newi = i.reshape(2,2,3)
newi

array([[[1, 2, 3],
        [4, 5, 3]],

       [[4, 5, 1],
        [2, 1, 3]]])

In [79]:
i

array([[1, 2, 3, 4],
       [5, 3, 4, 5],
       [1, 2, 1, 3]])

In [80]:
j = np.array([[1,2,3],[4,5,6]])
j

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
flatj = j.flatten()
flatj

array([1, 2, 3, 4, 5, 6])

In [82]:
newi.flatten()

array([1, 2, 3, 4, 5, 3, 4, 5, 1, 2, 1, 3])

In [88]:
i

array([[1, 2, 3, 4],
       [5, 3, 4, 5],
       [1, 2, 1, 3]])

In [91]:
i[:2, ::2]

array([[1, 3],
       [5, 4]])

In [92]:
i[0]

array([1, 2, 3, 4])

In [93]:
i[1]

array([5, 3, 4, 5])

In [94]:
i[0][2]

3

In [95]:
x = [[1,2,3],[4,5,6]]
x

[[1, 2, 3], [4, 5, 6]]

In [96]:
x[1]

[4, 5, 6]

In [97]:
x[1][1]

5

In [98]:
i

array([[1, 2, 3, 4],
       [5, 3, 4, 5],
       [1, 2, 1, 3]])

In [99]:
i[i>2]

array([3, 4, 5, 3, 4, 5, 3])

In [100]:
i = np.array([[1,20,13,14],
             [4,3,15,5],
             [1,12,10,3]])
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [102]:
t = i>5
t

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [103]:
i[t]

array([20, 13, 14, 15, 12, 10])

In [111]:
a = np.array([1,2,5,3])
a

array([1, 2, 5, 3])

In [114]:
a += 1

In [116]:
a -= 1

In [117]:
a

array([1, 2, 5, 3])

In [118]:
h = a * 3

array([ 3,  6, 15,  9])

In [119]:
a / 2

array([0.5, 1. , 2.5, 1.5])

In [120]:
a ** 3

array([  1,   8, 125,  27], dtype=int32)

In [121]:
i = np.array([[1,20,13,14],
             [4,3,15,5],
             [1,12,10,3]])
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [122]:
i.T

array([[ 1,  4,  1],
       [20,  3, 12],
       [13, 15, 10],
       [14,  5,  3]])

In [123]:
d = i.T
d.shape

(4, 3)

In [124]:
i.shape

(3, 4)

In [140]:
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [127]:
i.max()

20

In [128]:
i.min()

1

In [129]:
i.max(axis = 0)

array([ 4, 20, 15, 14])

In [130]:
i.max(axis = 1)

array([20, 15, 12])

In [133]:
i[:2,1:3].max(axis = 0)

array([20, 15])

In [134]:
i[:2,1:3].min(axis = 0)

array([ 3, 13])

In [135]:
i.sum()

101

In [136]:
i.cumsum()

array([  1,  21,  34,  48,  52,  55,  70,  75,  76,  88,  98, 101],
      dtype=int32)

In [137]:
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [138]:
i.cumsum(axis=0)

array([[ 1, 20, 13, 14],
       [ 5, 23, 28, 19],
       [ 6, 35, 38, 22]], dtype=int32)

In [139]:
i.cumprod()

array([         1,         20,        260,       3640,      14560,
            43680,     655200,    3276000,    3276000,   39312000,
        393120000, 1179360000], dtype=int32)

In [141]:
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [143]:
i.sum(axis = 1)

array([48, 27, 26])

In [214]:
f = np.random.randint(5, 10, (3,4,6, 2))
f

array([[[[7, 6],
         [7, 9],
         [8, 8],
         [5, 6],
         [9, 6],
         [8, 9]],

        [[9, 7],
         [6, 5],
         [5, 5],
         [7, 8],
         [5, 8],
         [9, 8]],

        [[7, 7],
         [9, 6],
         [7, 7],
         [6, 6],
         [5, 6],
         [9, 8]],

        [[6, 9],
         [7, 5],
         [9, 9],
         [7, 7],
         [9, 8],
         [5, 9]]],


       [[[8, 7],
         [7, 8],
         [5, 8],
         [6, 7],
         [8, 8],
         [9, 5]],

        [[8, 8],
         [6, 5],
         [5, 9],
         [8, 8],
         [8, 8],
         [6, 6]],

        [[8, 9],
         [6, 9],
         [5, 8],
         [9, 8],
         [8, 5],
         [8, 7]],

        [[6, 7],
         [7, 7],
         [8, 5],
         [7, 5],
         [7, 8],
         [7, 6]]],


       [[[9, 5],
         [6, 9],
         [9, 8],
         [8, 6],
         [6, 5],
         [8, 6]],

        [[6, 9],
         [6, 8],
         [6, 9],
         

In [215]:
np.random.uniform(10.5,20.6)

14.155526630450604

In [216]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[4,3],
             [1,2]])

In [217]:
a

array([[1, 2],
       [3, 4]])

In [218]:
b

array([[4, 3],
       [1, 2]])

In [219]:
a + b

array([[5, 5],
       [4, 6]])

In [220]:
a * b

array([[4, 6],
       [3, 8]])

In [221]:
a

array([[1, 2],
       [3, 4]])

In [222]:
b

array([[4, 3],
       [1, 2]])

In [223]:
a.dot(b)

array([[ 6,  7],
       [16, 17]])

In [224]:
v = 0.5
h = np.sin(v)
h

0.479425538604203

In [225]:
np.pi

3.141592653589793

In [227]:
np.sin(np.pi/4)

0.7071067811865476

In [228]:
np.exp(np.array([0,1,2,3]))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [229]:
np.sqrt(4)

2.0

In [230]:
i

array([[ 1, 20, 13, 14],
       [ 4,  3, 15,  5],
       [ 1, 12, 10,  3]])

In [235]:
np.sort(i, kind = "heapsort")

array([[ 1, 13, 14, 20],
       [ 3,  4,  5, 15],
       [ 1,  3, 10, 12]])

In [236]:
l = [1,2,3,4]

In [237]:
l

[1, 2, 3, 4]

In [238]:
c = np.asarray(l)
c

array([1, 2, 3, 4])

In [239]:
c = np.array(l)

In [240]:
c

array([1, 2, 3, 4])