In [1]:
import numpy as np
    

In [17]:
arr = np.array([[1.0,2.0,3],
               [4,5+0j,'sr']])
print (arr)
print('array type is', type(arr)) #type of array
print('No.of dimensions',arr.ndim) #dimensions or axes
print('shape of array',arr.shape) #shape of array
print('size of array',arr.size) #total number of elements
print(arr.dtype) #type of elements in array

[['1.0' '2.0' '3']
 ['4' '(5+0j)' 'sr']]
array type is <class 'numpy.ndarray'>
No.of dimensions 2
shape of array (2, 3)
size of array 6
<U64


In [11]:
arr = np.array([[[1,2,3],
               [4,5,6]]])  # brackets signfies dimesnions or axes
print(arr.ndim)
print(arr.shape)

3
(1, 2, 3)


In [22]:
z = np.array([[[1,2],[3,4]],
             [[5,6],[7,8]]])
print(z)
print(z.ndim)
print(z.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [26]:
arr2 = np.array([[1.0,2.0,3],
               [4,5,6]], dtype='float')
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
c= np.zeros((1,3,4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [35]:
c= np.ones((1,3,4))
print(c)
c.ndim

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


3

In [50]:
y= np.empty((5,3,4)) #0 is null, 1 is default
print(y)


[[[-2.64543722e-098  9.74894463e-312  9.74886088e-312 -1.36276480e+222]
  [ 9.74894458e-312  9.74886223e-312 -2.12688969e+212  9.74894458e-312]
  [ 9.74886223e-312 -5.07821142e-027  9.74894459e-312  9.74886222e-312]]

 [[-1.37130802e-110  9.74894459e-312  9.74886222e-312 -2.60776013e-036]
  [ 9.74894461e-312  9.74886217e-312 -3.18533777e+214  9.74894461e-312]
  [ 9.74886217e-312 -8.65050411e+299  9.74894461e-312  9.74886178e-312]]

 [[-9.77655876e+280  9.74894461e-312  9.74886178e-312 -7.63739863e+174]
  [ 9.74894461e-312  9.74886128e-312  3.77844912e+132  9.74894461e-312]
  [ 9.74886128e-312 -7.21303444e-001  9.74894447e-312  9.74884613e-312]]

 [[-6.70030069e+072  9.74894447e-312  9.74884613e-312 -1.27377985e+039]
  [ 9.74894461e-312  9.74886256e-312 -2.18915280e-230  9.74894461e-312]
  [ 9.74886256e-312  1.57588673e+127  9.74894463e-312  9.74860154e-312]]

 [[ 3.52928270e+093  9.74894463e-312  9.74860154e-312  5.63605110e+253]
  [ 9.74894463e-312  9.74860138e-312  1.78496776e+238  9

In [37]:
a = np.array((1,3,2))
print(a)
a.ndim

[1 3 2]


1

In [53]:
d = np.full((3,3),6, dtype = 'complex')
print('\n array intiailized with all 6. type is complex', d)


 array intiailized with all 6. type is complex [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [62]:
d = np.random.random((3,3))
print (d)

[[0.8174818  0.72712592 0.39935434]
 [0.06217838 0.6343724  0.78415327]
 [0.28457846 0.89291026 0.69107403]]


In [67]:
#sequence of numbers from 0 to 50 with a step value of 5
f = np.arange(0,30,5)
print('An array with steps of 5:',f)
print(f.ndim)

An array with steps of 5: [ 0  5 10 15 20 25]
1


In [77]:
#creating a sequence of 10 values in range 0 to 5
g = np.linspace(0,5,10)  # end value is number of sequence
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [80]:
i = np.array([[1,2,3,4],
             [5,3,4,5],
             [1,2,3,1]])
print(i)
print(i.ndim)
print(i.shape)

[[1 2 3 4]
 [5 3 4 5]
 [1 2 3 1]]
2
(3, 4)


In [86]:
newi = i.reshape(1,4,3)  # converts 2D to 3D array the total number of elements should be same as orginal array. eg 12 3*4 and 2*2*3, 1*3*4 
print(newi)
newi.ndim
# newi.shape

[[[1 2 3]
  [4 5 3]
  [4 5 1]
  [2 3 1]]]


3

In [91]:
## Array indexing

arr = np.array([[-1,2,3,4],
               [4,0,5,9],
               [3,4,5,6],
               [5,6,7,0.1]])

#slicing array
temp = arr [:4,::3] #first one signisfies the second one signifies the column, you can create  step value 
print(temp)

[[-1.   4. ]
 [ 4.   9. ]
 [ 3.   6. ]
 [ 5.   0.1]]


In [92]:
#integer array example
temp = arr[[0,1,2,3],[3,2,1,0]] #elements at indices (0,3),(1,2),(2,1),(3,0)
print(temp)

[4. 5. 4. 5.]


In [94]:
# temp = arr[[0,1,2,3],[3,2,1,0],[3,2,1,0]] # this is for 3 dimension array
# print(temp)

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [100]:
#boolean indexing
cond = arr>3
temp =arr[arr>3] #(elements greater than 3)
print(temp)


[4. 4. 5. 9. 4. 5. 6. 5. 6. 7.]


In [101]:
t = arr>3
t

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [109]:
import numpy as p
a = np.array([1,2,5,3])
#add 1 to every element
print(a+1)
#subtract 1 to every element
print(a-1)
#multiply 3 to every element
print(a*3)
#raise to the power 2
print(a**2)
print(a)
#double easch elemt and modify the array
a*=2
print(a)


[2 3 6 4]
[0 1 4 2]
[ 3  6 15  9]
[ 1  4 25  9]
[1 2 5 3]
[ 2  4 10  6]


In [112]:
a = np.array([[-1,2,3,4],
               [4,0,5,9],
               [3,4,5,10]])
print(a)
print(a.shape)

[[-1  2  3  4]
 [ 4  0  5  9]
 [ 3  4  5 10]]
(3, 4)


In [113]:
b= a.T
print(b)
print(b.shape)

[[-1  4  3]
 [ 2  0  4]
 [ 3  5  5]
 [ 4  9 10]]
(4, 3)


In [123]:
b.max()
b[:3,1:3].max(axis=0)
b.min(axis=1) #axis 1 signifies rows

array([-1,  0,  3,  4])

In [124]:
b[1:3,1:3].max(axis=1)

array([4, 5])

In [120]:
b.min(axis=0)  #axis 0 signifies columns

array([-1,  0,  3])

In [121]:
b.sum()

48

In [122]:
b.cumsum(axis=0) #cumulative sum along colums adds every sum of element before the element 

array([[-1,  4,  3],
       [ 1,  4,  7],
       [ 4,  9, 12],
       [ 8, 18, 22]], dtype=int32)

In [125]:
b.cumsum(axis=1)

array([[-1,  3,  6],
       [ 2,  2,  6],
       [ 3,  8, 13],
       [ 4, 13, 23]], dtype=int32)

In [126]:
b.cumprod(axis=0)

array([[ -1,   4,   3],
       [ -2,   0,  12],
       [ -6,   0,  60],
       [-24,   0, 600]], dtype=int32)

In [129]:
b.cumprod(axis=1)

array([[ -1,  -4, -12],
       [  2,   0,   0],
       [  3,  15,  75],
       [  4,  36, 360]], dtype=int32)

In [135]:
#Random array generation

f = np.random.randint(5,20,8)  #1.low value, 2.highest value, 3.number of values b/w high and low
f

array([17,  8,  5, 19,  6, 17, 17, 16])

In [143]:
f = np.random.randint(5,20,(3,4,6)) #creates array b/w high and low d is depth/layers, then rows and then colums, 
#last data 20 will be exlsuive
f #3D array of random arranges

array([[[19, 12, 13,  6,  9,  6],
        [ 7, 12,  9,  6,  5,  5],
        [17, 16, 12, 17, 17,  8],
        [17, 14,  8, 15, 17,  5]],

       [[10, 16,  6, 12, 13, 13],
        [12,  7, 14, 11,  9, 13],
        [16,  6, 12, 18,  5, 16],
        [10, 14, 14, 11, 19, 19]],

       [[16, 13, 16, 12,  7,  5],
        [ 8,  8, 16, 10, 11,  9],
        [ 7,  7, 15, 13,  9, 17],
        [ 7, 10,  8, 14, 10, 10]]])

In [146]:
f = np.random.randint(5,20,(1,4))
f

array([[ 9, 11, 10,  6]])

In [148]:
f = np.random.uniform(1.5,7.5,(1,4)) #returns a random float number
f

array([[3.250478  , 5.79227203, 4.89156391, 6.73897246]])

In [151]:
f = np.round(random.uniform(1.55,7.55),2)
f

NameError: name 'random' is not defined

In [156]:
h = np.random.SystemRandom().uniform(5,10)
h


AttributeError: module 'numpy.random' has no attribute 'SystemRandom'

In [163]:
f = np.random.uniform(3,4,(3,3,4)) #returns a random array of floats
f

array([[[3.47386765, 3.2280175 , 3.17021619, 3.50061602],
        [3.3929933 , 3.38147726, 3.09410995, 3.46414438],
        [3.07108091, 3.9615993 , 3.34472519, 3.90746433]],

       [[3.21045251, 3.19165732, 3.69177007, 3.76671287],
        [3.24619865, 3.12975265, 3.46911904, 3.34904106],
        [3.67082556, 3.15320775, 3.3758281 , 3.62376627]],

       [[3.46141968, 3.82018618, 3.59389315, 3.54303311],
        [3.74915714, 3.29881744, 3.4407107 , 3.0202153 ],
        [3.01173678, 3.57231765, 3.00416969, 3.61568192]]])

In [171]:
# binary operation

#addition
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
            [7,8]])

print(a+b)
print(a*b) # scalar multiplication each element in array A with its corresponding element in array B

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [170]:
#multiplication
a = np.array([[1,2,3],
             [3,4,3],
             [2,0,1]])
b = np.array([[5,6],
            [7,8],
             [4,3]])
print(a.dot(b)) # matrix multiplcation

[[31 31]
 [55 59]
 [14 15]]


In [185]:

Universal function
a = np.array([[1,2],
            [3,4]])
             
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [187]:
a = np.array([[1,2],
            [3,4]])
b = np.array([[5,6],
            [7,8]])
print(np.sum(a+b))
print(np.subtract(a-b))

36


ValueError: invalid number of arguments

In [193]:
a = np.array([[-1,2,3,4],
               [4,0,5,9],
               [3,4,5,10]])
np.sort(a,axis=0)

array([[-1,  0,  3,  4],
       [ 3,  2,  5,  9],
       [ 4,  4,  5, 10]])

In [194]:
np.sort(a,kind = 'mergesort')

array([[-1,  2,  3,  4],
       [ 0,  4,  5,  9],
       [ 3,  4,  5, 10]])

In [195]:
np.sort(a,kind = 'heapsort')

array([[-1,  2,  3,  4],
       [ 0,  4,  5,  9],
       [ 3,  4,  5, 10]])

In [200]:
#sort names in array

d = [('name','S10'),('grad_yr', int), ('cgpa', float)]
values = [('ABC',2009, 8.5), ('XYZ',2008, 9.6),('LMN',2008, 8.6) ]
arr = np.array(values, dtype = d)
print("sort by name",np.sort(arr, order= 'name'))
print('sort by grad_year and then Cgpa', np.sort(arr,order=['grad_yr','cgpa']))

sort by name [(b'ABC', 2009, 8.5) (b'LMN', 2008, 8.6) (b'XYZ', 2008, 9.6)]
sort by grad_year and then Cgpa [(b'LMN', 2008, 8.6) (b'XYZ', 2008, 9.6) (b'ABC', 2009, 8.5)]
